// Foundation, edit with care
// Picks the build-time share card (Open Graph image) for a route.
//
// THE CONVENTION. `npm run og:pages` (scripts/generate-og-pages.mjs) writes one
// branded 1200x630 PNG per page into public/og/, named after the route:
//   `/`                 -> /og/home.png
//   `/contact`          -> /og/contact.png
//   `/journal/my-post`  -> /og/journal-my-post.png
// BaseLayout uses that card when a page has no photo of its own to share.
//
// WHY THE FILE LIST IS AN ARGUMENT (PORTS.md card 59). This used to build the
// path and return it unconditionally, while its comment promised a fallback to
// og-default.png "if the slug-specific file isn't there". Nothing checked. So
// every route without a PNG (every custom page, every journal post without a
// cover photo) advertised a share image that 404s, and Facebook, iMessage and
// Slack showed a link with no picture. And because the starter still carried
// the Reid Design build's PNGs, a fresh fork's home page shared as "Reid Design
// LLC" until someone regenerated them. The caller now passes the set of files
// that actually exist, so a missing card falls back instead of breaking.
//
// Kept pure (no fs, no import.meta) so it runs anywhere and is unit tested in
// og-image.test.ts. BaseLayout builds the set with import.meta.glob.

/** Served path of the site-wide fallback card, regenerated by `npm run og`. */
export const DEFAULT_OG_PATH = '/og-default.png';

/**
 * Turn a route pathname into its conventional card path.
 * Leading and trailing slashes are dropped, inner slashes become dashes, and
 * the home page is `home`.
 */
export function ogPathForRoute(pathname: string): string {
  const trimmed = pathname.replace(/^\/+|\/+$/g, '');
  if (!trimmed) return '/og/home.png';
  return `/og/${trimmed.replace(/\//g, '-')}.png`;
}

/**
 * The card to share for `pathname`: its own generated card when that file is
 * in `available`, otherwise the site-wide default.
 *
 * @param available served paths of the cards that exist, e.g. `/og/home.png`.
 */
export function ogImageForRoute(pathname: string, available: ReadonlySet<string>): string {
  const own = ogPathForRoute(pathname);
  return available.has(own) ? own : DEFAULT_OG_PATH;
}

/**
 * Convert the keys `import.meta.glob('/public/og/*.png')` returns
 * (`/public/og/home.png`) into the paths the site serves them at
 * (`/og/home.png`). Anything outside /public/og/ is ignored.
 */
export function servedOgPaths(globKeys: Iterable<string>): Set<string> {
  const served = new Set<string>();
  for (const key of globKeys) {
    if (key.startsWith('/public/og/')) served.add(key.slice('/public'.length));
  }
  return served;
}
